# SPDX-License-Identifier: Apache-2.0
"""Meridian V1 engine-neutral query contract and planning library.

This package deliberately does not define a ``query`` Catalog. Consumers use a
registered Catalog such as ``structured``; Catalog implementers and Adapters
reuse the values exported here.
"""

from ._version import __version__
from .adapter import (
    CompiledQuery,
    NormalizedQueryResult,
    QueryCapabilities,
    QueryTranslator,
    TranslationContext,
    assert_translation_contract,
    enforce_result_budget,
)
from .ast import (
    Aggregate,
    BinaryExpression,
    BooleanExpression,
    Distance,
    DistanceWithin,
    DocumentPath,
    Field,
    FullTextMatch,
    Literal,
    MembershipExpression,
    NamedAggregate,
    NullTest,
    Parameter,
    Point,
    Projection,
    Sort,
    TimestampRange,
    UnaryExpression,
    ValueExpression,
    distance,
    distance_within,
    expression,
    expression_from_dict,
    field,
    full_text,
    literal,
    parameter,
    parse_filter,
    point,
    timestamp_range,
)
from .builder import MeridianQuery, query
from .contracts import (
    query_capability_contract,
    query_cursor_contract,
    query_operation_contract,
    query_public_api_contract,
)
from .cursor import CURSOR_FORMAT_VERSION, CursorExpectations, CursorPayload, CursorSigner
from .diagnostics import Diagnostic, ExplainRecord, Severity, redact
from .errors import (
    CrossBindingOperation,
    ExcessiveBudget,
    FieldTypeMismatch,
    InvalidCursor,
    InvalidTraversal,
    NondeterministicOrdering,
    QueryCompatibilityError,
    QueryValidationError,
    StaleRegistryPlan,
    UnknownResource,
    UnknownSchema,
    UnsafeResidual,
    UnsupportedSemantic,
)
from .normalize import normalize_builder, normalize_expression
from .planner import (
    ImplementationMode,
    PlannedQuery,
    QueryPlanner,
    ResidualInput,
    ResidualRule,
    RewriteRule,
    compile_query,
)
from .requirements import RequirementGraph, SemanticRequirement, infer_requirements
from .validation import (
    CompileValidation,
    RegistryView,
    ResolvedResource,
    StartupResourceRequirement,
    StartupValidation,
    validate_compile,
    validate_startup,
)
from .wire import (
    NO_EXTENSIONS,
    QUERY_CAPABILITY_FORMAT_VERSION,
    QUERY_CONTRACT_VERSION,
    QUERY_FORMAT_VERSION,
    ExtensionPolicy,
    Join,
    PageSpec,
    QueryOperation,
    QueryTarget,
    ResultSpec,
    SafetyBudget,
    TraversalSpec,
)

__all__ = [
    "CURSOR_FORMAT_VERSION",
    "NO_EXTENSIONS",
    "QUERY_CAPABILITY_FORMAT_VERSION",
    "QUERY_CONTRACT_VERSION",
    "QUERY_FORMAT_VERSION",
    "Aggregate",
    "BinaryExpression",
    "BooleanExpression",
    "CompileValidation",
    "CompiledQuery",
    "CrossBindingOperation",
    "CursorExpectations",
    "CursorPayload",
    "CursorSigner",
    "Diagnostic",
    "Distance",
    "DistanceWithin",
    "DocumentPath",
    "ExcessiveBudget",
    "ExplainRecord",
    "ExtensionPolicy",
    "Field",
    "FieldTypeMismatch",
    "FullTextMatch",
    "ImplementationMode",
    "InvalidCursor",
    "InvalidTraversal",
    "Join",
    "Literal",
    "MembershipExpression",
    "MeridianQuery",
    "NamedAggregate",
    "NondeterministicOrdering",
    "NormalizedQueryResult",
    "NullTest",
    "PageSpec",
    "Parameter",
    "PlannedQuery",
    "Point",
    "Projection",
    "QueryCapabilities",
    "QueryCompatibilityError",
    "QueryOperation",
    "QueryPlanner",
    "QueryTarget",
    "QueryTranslator",
    "QueryValidationError",
    "RegistryView",
    "RequirementGraph",
    "ResidualInput",
    "ResidualRule",
    "ResolvedResource",
    "ResultSpec",
    "RewriteRule",
    "SafetyBudget",
    "SemanticRequirement",
    "Severity",
    "Sort",
    "StaleRegistryPlan",
    "StartupResourceRequirement",
    "StartupValidation",
    "TimestampRange",
    "TranslationContext",
    "TraversalSpec",
    "UnaryExpression",
    "UnknownResource",
    "UnknownSchema",
    "UnsafeResidual",
    "UnsupportedSemantic",
    "ValueExpression",
    "__version__",
    "assert_translation_contract",
    "compile_query",
    "distance",
    "distance_within",
    "enforce_result_budget",
    "expression",
    "expression_from_dict",
    "field",
    "full_text",
    "infer_requirements",
    "literal",
    "normalize_builder",
    "normalize_expression",
    "parameter",
    "parse_filter",
    "point",
    "query",
    "query_capability_contract",
    "query_cursor_contract",
    "query_operation_contract",
    "query_public_api_contract",
    "redact",
    "timestamp_range",
    "validate_compile",
    "validate_startup",
]
